# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ea84e04909a65feafb3c8232b2775fe1c55699cf842b5907a37d463f2bfc1b787687901f5f725e8b995bcaf615f4ef1a4ebdce87bdeb49c032bf79b8fc693f

test:
  secret_key_base: e76de014942f2a52f9975ddde1a507d72593c3dca5bec0cbd4fe2bb11b0acccdddc3a54a1162297ae434fc3ebd9f86a9bfcf9b2d84259c379b039093769cb3c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
